pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        sh 'mvn clean install'
        sh 'g++ -o new_exec new.cpp'
        sh 'echo "Build Stage Successul"'
      }
    }
    stage('Test') {
      steps {
          sh './your_executable'
          sh 'mvn test'
          sh 'echo "Test Stage Successful"'
      }
    }
    stage('Deploy') {
      steps {
        sh 'mvn deploy'
        echo 'Deployment Successful'
      }
    }
  }
  post {
    failure {
      echo 'Pipeline failed'
    }
  }
}
